Started at: 
Sat Dec  9 12:04:45 CET 2023
Instance 7
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 0.09368538856506348 s
number of sums: 511
number of prods: 4096
Starting optimization
     fun: 0.4500000000000006
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
Optimization time: 111.05076742172241 s
Target equation: 0.9999999999999835
Sum of optimizable facts = 0.4500000000000006
Optimal probabilities
[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]

real	1m52.538s
user	1m51.982s
sys	0m0.259s
Ended at: 
Sat Dec  9 12:06:37 CET 2023
